// <auto-generated />
using System;
using EFGetStarted.AspNetCore.NewDb.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BracketMap.Web.Migrations
{
    [DbContext(typeof(BracketMapContext))]
    [Migration("20190810001349_FixPropSpelling")]
    partial class FixPropSpelling
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0-preview7.19362.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EFGetStarted.AspNetCore.NewDb.Models.NodeMap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Victor");

                    b.HasKey("Id");

                    b.ToTable("NodeMaps");
                });

            modelBuilder.Entity("EFGetStarted.AspNetCore.NewDb.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<int?>("NodeMapId");

                    b.HasKey("Id");

                    b.HasIndex("NodeMapId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("EFGetStarted.AspNetCore.NewDb.Models.Tournement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<int>("PlayerCount");

                    b.HasKey("Id");

                    b.ToTable("Tournements");
                });

            modelBuilder.Entity("EFGetStarted.AspNetCore.NewDb.Models.Player", b =>
                {
                    b.HasOne("EFGetStarted.AspNetCore.NewDb.Models.NodeMap", null)
                        .WithMany("Players")
                        .HasForeignKey("NodeMapId");
                });
#pragma warning restore 612, 618
        }
    }
}
