// <auto-generated />
using System;
using BracketMap.DAL.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BracketMap.DAL.Migrations
{
    [DbContext(typeof(BracketMapContext))]
    partial class BracketMapContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0-preview7.19362.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BracketMap.DAL.Models.BracketData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("TournamentId");

                    b.Property<int>("Victor");

                    b.HasKey("Id");

                    b.ToTable("NodeMaps");
                });

            modelBuilder.Entity("BracketMap.DAL.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BracketDataId");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("BracketDataId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("BracketMap.DAL.Models.Tournament", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<int>("PlayerCount");

                    b.HasKey("Id");

                    b.ToTable("Tournaments");
                });

            modelBuilder.Entity("BracketMap.DAL.Models.Player", b =>
                {
                    b.HasOne("BracketMap.DAL.Models.BracketData", null)
                        .WithMany("PlayerId")
                        .HasForeignKey("BracketDataId");
                });
#pragma warning restore 612, 618
        }
    }
}
